### ISSUE TITLE
support for advanced layouts

### ISSUE THREAD

**Issue by mikeal** [ipld/js-ipld-schema#2]
The following IPLD schema

```
type Hamt {String:FileUnion}<HAMT>
```

Produces the following error:

```
SyntaxError: Expected "#", "bool", "bytes", "enum", "float", "int", "link", "list", "map", "string", "struct", "union", or [ \t\n\r] but "{" found.
```

I tried changing it to the simpler form `type Hamt map<HAMT>` but that produces the following error:

```
SyntaxError: Expected "#", "type", "{", [ \t\n\r], or end of input but "<" found.
```

**Comment by mikeal** [comment]
Upon further inspection, the keyword `advanced` is also not supported. I’ve updated the title of this issue accordingly.

**Comment by rvagg** [comment]
there's a few versions of this syntax floating around, we need to firm up on one in ipld/specs/schemas, will propose something.

**Comment by rvagg** [comment]
done
